channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - bioconda::fastp =0.13.1
  - bioconda::gatk4 =4.0.4.0
  - bioconda::picard =2.18.9
  - python =3.6
  - bcftools =1.9
  - samtools =1.9
  - bwa =0.7.17
  - pygraphviz =1.3
  - pandas =0.25.3
